from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, ForeignKey, Float
from sqlalchemy.orm import relationship
from datetime import datetime
from database import Base


class Topic(Base):
    __tablename__ = "topics"

    id = Column(Integer, primary_key=True, index=True)
    slug = Column(String, unique=True, nullable=False)  # e.g. "sql-injection"
    name = Column(String, nullable=False)               # e.g. "SQL Injection"
    category = Column(String, nullable=False)           # e.g. "OWASP", "Fundamentals"
    difficulty = Column(Integer, default=1)             # 1-5
    description = Column(Text, nullable=True)
    prerequisites = Column(Text, default="[]")          # JSON list of topic slugs
    theory_content = Column(Text, nullable=True)        # JSON blob generated by Gemini
    lab_type = Column(String, nullable=True)            # "dvwa_sqli", "dvwa_xss", etc.
    order_index = Column(Integer, default=0)            # for display ordering

    # Relationships
    user_progress = relationship("UserTopicProgress", back_populates="topic")
    exercises = relationship("Exercise", back_populates="topic", cascade="all, delete-orphan")


class UserTopicProgress(Base):
    __tablename__ = "user_topic_progress"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    topic_id = Column(Integer, ForeignKey("topics.id"), nullable=False)
    theory_completed = Column(Boolean, default=False)
    lab_completed = Column(Boolean, default=False)
    quiz_score = Column(Float, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    xp_awarded = Column(Integer, default=0)

    # Relationships
    user = relationship("User", back_populates="topic_progress")
    topic = relationship("Topic", back_populates="user_progress")
